// <auto-generated />
using KeysRegister.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KeysRegister.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KeysRegister.Entities.Identifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RfidCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RfidCode")
                        .IsUnique();

                    b.ToTable("Identifiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Dział IT",
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            RfidCode = "0010614285",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dział Transportu",
                            FirstName = "Arkadiusz",
                            LastName = "Nowak",
                            RfidCode = "0004714539",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "100",
                            FirstName = "DZG27216",
                            LastName = "",
                            RfidCode = "0011079912",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Description = "185",
                            FirstName = "DZG27215",
                            LastName = "",
                            RfidCode = "0004861400",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "185",
                            FirstName = "DZG00009",
                            LastName = "",
                            RfidCode = "0004734756",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Description = "188",
                            FirstName = "DZG10001",
                            LastName = "",
                            RfidCode = "0004968393",
                            Type = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
